export const FETCHLOADING="FETCHLOADING"
export const FETCHDATA="FETCHDATA"
export const FETCHFURNITURE="FETCHFURNITURE"
export const SINGLEDATA="SINGLEDATA"
export const FETCHERROR="FETCHERROR"

export const SIGNIN="SIGNIN"